site_name: DAPI - DesignSafe API
site_description: User documentation for the DesignSafe API (dapi) package
site_author: Krishna Kumar, Pedro Arduino, Scott Brandenberg
site_url: https://designsafe-ci.github.io/dapi
repo_url: https://github.com/DesignSafe-CI/dapi
repo_name: DesignSafe-CI/dapi

theme:
  name: material
  logo: nheri.png
  favicon: favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: 
    - Overview: index.md
  - Getting Started:
    - Installation: installation.md
    - Authentication: authentication.md
    - Quick Start: quickstart.md
  - User Guide:
    - Jobs: jobs.md
    - Database Access: database.md
  - Examples:
    - Overview: examples.md
    - MPM Job Submission: examples/mpm.md
    - OpenSees Job Submission: examples/opensees.md
    - Database Queries: examples/database.md
  - API Reference:
    - Overview: api/index.md
    - DSClient: api/client.md
    - Jobs: api/jobs.md
    - Files: api/files.md
    - Apps: api/apps.md
    - Systems: api/systems.md
    - Database: api/database.md
    - Auth: api/auth.md
    - Exceptions: api/exceptions.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DesignSafe-CI/dapi
  css:
    - stylesheets/extra.css